version: '3'

services:
  proxy:
    build: ./
    depends_on:
        - 'checkout'
        - 'carousel'
    ports: 
        - '3000:3000'

  checkout:
    build: ../checkout/
    depends_on:
      - 'database'
    ports: 
      - '2000:2000'
  
  carousel:
    build: ../carousel/
    depends_on:
      - 'database'
    ports: 
      - '2500:2500'
  
  database:
    image: mongo:latest